name: DANCer
channels:
  - conda-forge
  - bioconda
  - anaconda
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - absl-py=2.1.0
  - argcomplete=3.3.0
  - astunparse=1.6.3
  - binutils_impl_linux-64=2.40
  - bioconductor-annotationdbi=1.64.1
  - bioconductor-biobase=2.62.0
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biostrings=2.70.1
  - bioconductor-data-packages=20231203
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-go.db=3.18.0
  - bioconductor-impute=1.76.0
  - bioconductor-iranges=2.36.0
  - bioconductor-keggrest=1.42.0
  - bioconductor-preprocesscore=1.64.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - brotli-python=1.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - curl=8.8.0
  - expat=2.6.2
  - flatbuffers=24.3.25
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gast=0.5.4
  - gcc_impl_linux-64=13.2.0
  - gfortran_impl_linux-64=13.2.0
  - giflib=5.2.2
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.62.2
  - gxx_impl_linux-64=13.2.0
  - h5py=3.11.0
  - harfbuzz=8.5.0
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - jq=1.7.1
  - keras=3.3.3
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgomp=13.2.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsanitizer=13.2.0
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - make=4.3
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - ml_dtypes=0.3.2
  - namex=0.0.8
  - ncurses=6.5
  - numpy=1.26.4
  - oniguruma=6.9.9
  - openssl=3.3.1
  - opt_einsum=3.3.0
  - optree=0.11.0
  - packaging=24.0
  - pandas=2.2.2
  - pandoc=3.2
  - pango=1.52.2
  - pcre2=10.43
  - pip=24.0
  - pixman=0.43.2
  - protobuf=4.25.3
  - pthread-stubs=0.4
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-flatbuffers=24.3.25
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - r-askpass=1.2.0
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.4
  - r-bslib=0.7.0
  - r-cachem=1.1.0
  - r-checkmate=2.3.1
  - r-cli=3.6.2
  - r-cluster=2.1.6
  - r-codetools=0.2_20
  - r-colorspace=2.1_0
  - r-cpp11=0.4.7
  - r-crayon=1.5.2
  - r-curl=5.1.0
  - r-data.table=1.15.2
  - r-dbi=1.2.3
  - r-deldir=2.0_4
  - r-deoptimr=1.1_3
  - r-digest=0.6.35
  - r-doparallel=1.0.17
  - r-dynamictreecut=1.63_1
  - r-ellipsis=0.3.2
  - r-evaluate=0.23
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastcluster=1.2.6
  - r-fastmap=1.2.0
  - r-fit.models=0.64
  - r-fontawesome=0.5.2
  - r-foreach=1.5.2
  - r-foreign=0.8_86
  - r-formula=1.2_5
  - r-fs=1.6.4
  - r-ggplot2=3.5.1
  - r-glue=1.7.0
  - r-gridextra=2.3
  - r-gtable=0.3.5
  - r-highr=0.11
  - r-hmisc=5.1_3
  - r-htmltable=2.4.2
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httr=1.4.7
  - r-interp=1.1_6
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jpeg=0.1_10
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-knitr=1.47
  - r-labeling=0.4.3
  - r-lattice=0.22_6
  - r-latticeextra=0.6_30
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-mass=7.3_60
  - r-matrix=1.6_5
  - r-matrixstats=1.3.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-munsell=0.5.1
  - r-mvtnorm=1.2_5
  - r-nlme=3.1_164
  - r-nnet=7.3_19
  - r-openssl=2.2.0
  - r-pcapp=2.0_4
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-png=0.1_8
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.12
  - r-rcppeigen=0.3.4.0.0
  - r-rcurl=1.98_1.14
  - r-rlang=1.1.4
  - r-rmarkdown=2.27
  - r-robust=0.7_4
  - r-robustbase=0.99_2
  - r-rpart=4.1.23
  - r-rrcov=1.7_5
  - r-rsqlite=2.3.4
  - r-rstudioapi=0.16.0
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-survival=3.7_0
  - r-sys=3.4.2
  - r-tibble=3.2.1
  - r-tinytex=0.51
  - r-utf8=1.2.4
  - r-vctrs=0.6.5
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-wgcna=1.71
  - r-withr=3.0.0
  - r-xfun=0.44
  - r-yaml=2.3.8
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - rich=13.7.1
  - sed=4.8
  - setuptools=70.0.0
  - six=1.16.0
  - snappy=1.2.0
  - sysroot_linux-64=2.12
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - tensorflow=2.16.1
  - tensorflow-base=2.16.1
  - tensorflow-estimator=2.16.1
  - termcolor=2.4.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomlkit=0.12.5
  - typing-extensions=4.12.1
  - typing_extensions=4.12.1
  - tzdata=2024a
  - urllib3=2.2.1
  - werkzeug=3.0.3
  - wheel=0.43.0
  - wrapt=1.16.0
  - xmltodict=0.13.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yq=3.4.3
  - zipp=3.17.0
  - zlib=1.3.1
  - zstd=1.5.6
